---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# NeoRun

EPSON のSF810 がNeoRunにuploadしたデータのbackup形式をもとに、分析をするツール

## Installation

以下のようにしてインストールできます。

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("419kfj/NeoRun")
```

## Example

NeoRunから、backup形式でダウンロードしたファイル（csv）を入力としてRのデータフレームに変換します。

```{r example}
library(psych)
library(tidyverse)
library(NeoRun)
```

```{r}
# sample data としてついてます。"20170801-20170801.csv"

fname <- "inst/extdata/20170801-20170801.csv"
res <-  NeoRun_data(fname)

res$base # Data Description
names(res$Lap) # 要約されたLapデータ
nrow(res$Lap)
names(res$Graph) # GPS data
nrow(res$Graph)
summary(res$Graph)
```

```{r}
names(res$Graph)
res$Graph %>% select("GraphDistance","GraphSpeed","HeartRate") %>%
  pairs.panels(main=res$base)
```

# 宇都宮マラソン2016のデータ
```{r}
fname = "inst/extdata/20151115-20151115.csv"
res <-  NeoRun_data(fname)
```

```{r}
names(res$Graph)
res$Graph %>% select("GraphDistance","GraphSpeed","GraphPitch","GraphStride","HeartRate") %>%
  pairs.panels(main=res$base)
```

```{r}
res$Graph %>% select("HeartRate") %>% unlist() %>% hist()
```

